[package]
name = "zune-ppm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zune-core = "0.2.1"
log = "0.4.17"