## Add tests to ensure no-std crates are no-std
name: Build no std

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
        # Target below does not have a standard library
      - run: rustup target add x86_64-unknown-uefi
        # Below targets run in no-std environments
      - run: cargo build -p zune-core     --target x86_64-unknown-uefi --no-default-features --features log,serde
      - run: cargo build -p zune-inflate  --target x86_64-unknown-uefi --no-default-features --features zlib,gzip
      - run: cargo build -p zune-jpeg     --target x86_64-unknown-uefi --no-default-features --features log,x86,neon
      - run: cargo build -p zune-png      --target x86_64-unknown-uefi --no-default-features --features log,libm
      - run: cargo build -p zune-ppm      --target x86_64-unknown-uefi --no-default-features --features log
      - run: cargo build -p zune-qoi      --target x86_64-unknown-uefi --no-default-features --features log
      - run: cargo build -p zune-farbfeld --target x86_64-unknown-uefi --no-default-features --features log
      - run: cargo build -p zune-psd      --target x86_64-unknown-uefi --no-default-features --features log
      - run: cargo build -p zune-bmp      --target x86_64-unknown-uefi --no-default-features --features log,rgb_inverse
      - run: cargo build -p zune-gif      --target x86_64-unknown-uefi --no-default-features --features log
      - run: cargo build -p zune-hdr      --target x86_64-unknown-uefi --no-default-features --features log,libm
      - run: cargo build -p zune-jpegxl   --target x86_64-unknown-uefi --no-default-features --features log


