name: Test

on:
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main","dev" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.toolchain }} ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest]
        target: [""]
        toolchain: [stable, nightly]
        include:
          - os: ubuntu-latest
            toolchain: 1.87  # MSRV
          - os: windows-latest
            toolchain: stable
            test-args: --exclude zune-benches --exclude zune-image --exclude zune-imageprocs --exclude zune-png
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.target }}

      # portable_simd feature is incompatible with stable, so don't always use --all-features
      - run: cargo test 
                ${{ matrix.toolchain == 'nightly' && '--all-features' || ''}}
                ${{ matrix.target && format('--target {0}', matrix.target) || ''}}
                --verbose 
                --workspace 
                --no-fail-fast 
                ${{ matrix.test-args }}
